name: Release

on:
  create:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    #if: github.event.base_ref == 'refs/heads/main'
    steps:
      - name: Event
        run: echo ${{ toJson(github.event) }}
